[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "D", "YTT", "PL", "T20", "RSE", "RET", "SIM", "TID",
    "TCH", "ARG", "PTH", "S", "ANN", "B"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []
fix-only = true
show-fixes = true
show-source = true
#fix = true
format = "grouped"

# Tags
task-tags = ["TODO", "FIXME", "todo", "fixme"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
# Per File

# Same as Black.
line-length = 100

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py311"


[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.ruff.per-file-ignores]

[tool.ruff.flake8-annotations]
allow-star-arg-any = false
ignore-fully-untyped = true
mypy-init-return = false
suppress-dummy-args = false
suppress-none-returning = false
[tool.ruff.flake8-bandit]
check-typed-exception = false
#hardcoded-tmp-directory = []
#extend-hardcoded-tmp-directory = [""]
[tool.ruff.flake8-bugbear]
#extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
[tool.ruff.flake8-builtins]
#builtins-ignorelist = [""]
[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true
[tool.ruff.flake8-errmsg]
max-string-length = 20
[tool.ruff.flake8-gettext]
#extend-function-names = ["ugettetxt"]
#function-names = ["_", "gettext", "ngettext", "ugettetxt"]
[tool.ruff.flake8-implicit-str-concat]
#setting allow-multiline = false should
#typically be coupled with disabling explicit-string-concatenation
allow-multiline = true
[tool.ruff.flake8-import-conventions]
[tool.ruff.flake8-import-conventions.aliases]
# Declare the default aliases.
# Declare the banned aliases.
# Declare the banned `from` imports.
# Declare a custom alias for the `matplotlib` module
[tool.ruff.flake8-pytest-style]
#fixture-parentheses = true
#mark-parentheses = true
#parametrize-names-type = "list"
#parametrize-values-row-type = "list"
#parametrize-values-type = "list"
#raises-extend-require-match-for = ["requests.RequestException"]
#raises-require-match-for = ["requests.RequestException"]

[tool.ruff.flake8-quotes]
avoid-escape = false
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"
[tool.ruff.flake8-self]
#ignore-names = ["_new"]
[tool.ruff.flake8-tidy-imports]
#ban-relative-imports = "all"
[tool.ruff.flake8-tidy-imports.banned-api]
[tool.ruff.flake8-type-checking]
#exempt-modules = ["typing", "typing_extensions"]
#runtime-evaluated-base-classes = ["pydantic.BaseModel"]
#runtime-evaluated-decorators = ["attrs.define", "attrs.frozen"]
strict = false
[tool.ruff.flake8-unused-arguments]
ignore-variadic-names = true
[tool.ruff.isort]
#classes = ["SVC"]
#constants = ["constant"]
#variables = ["VAR"]
#extra-standard-library = ["path"]
force-single-line = true
force-sort-within-sections = true
#force-to-top = ["src"]
#forced-separate = ["tests"]
force-wrap-aliases = true
combine-as-imports = true
known-first-party = ["src"]
#known-local-folder = ["src"]
#known-third-party = ["src"] # TODO: Add all third-party packages for packages.
#lines-after-imports = 1
lines-between-types = 1
#no-lines-before = ["future", "standard-library","third-party","first-party","local-folder","str"]
order-by-type = true
#relative-imports-order = "closest-to-furthest
#required-imports = ["from __future__ import annotations"]
#section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
#single-line-exclusions = ["os", "json"]
#split-on-trailing-comma = false
#[tool.ruff.isort.sections]
# Group all * imports into a/own/separate section.
[tool.ruff.pep8-naming]
#classmethod-decorators = ["pydantic.validator"]
#ignore-names = [""]
#staticmethod-decorators = ["stcmthd"]
[tool.ruff.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 100
[tool.ruff.pydocstyle]
convention = "google"
#ignore-decorators = ["typing.overload"]
#property-decorators = ["gi.repository.GObject.Property"]
[tool.ruff.pylint]
#allow-magic-value-types = ["int"]
#Type: list["str" | "bytes" | "complex" | "float" | "int" | "tuple"]
max-args = 6
max-branches = 12
max-returns = 6
max-statements = 50
[tool.ruff.pyupgrade]
keep-runtime-typing = true

# @todo: Add support for `mypy` static typing configuration.
[tool.mypy]
#Examples
##Imports
#mypy_path = ["src"] # https://mypy.readthedocs.io/en/stable/config_file.html#confval-mypy_path
#files = ["src"]
#modules = ["src"]
#packages = ["src"]
#exclude
namespace_packages = true
#current directory, or a member of the MYPYPATH environment variable or mypy_path config
explicit_package_bases = false
ignore_missing_imports = false
follow_imports = "skip"
#follow_imports_for_stubs = true
#python_executable = "python3.11"
no_site_packages = false
no_silence_site_packages = false
## Platform Configuration
python_version = "3.11"
#platform = "linux"
#always_true = ["tests"]
#always_false = ["tests"]
##Dynamic Typing
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = false
disallow_subclassing_any = false
#Untyped
disallow_untyped_calls = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
## None/Optionals - Flip values
implicit_optional = true
strict_optional = false
## Warnings
warn_redundant_casts = true
warn_unused_ignores = true
#warn_no_return = true #
#warn_return_any = true
warn_unreachable = true
ignore_errors = false
#Miscellaneous strictness
allow_untyped_globals = false
allow_redefinition = false
#local_partial_types = false
#enable_error_code = ["",""]
#disable_error_code = ["",""]
implicit_reexport = true
strict_concatenate = false
strict_equality = false
strict = false
## Config Error Messages
show_error_context = true
show_column_numbers = true
hide_error_codes = false
pretty = true
color_output = true
error_summary = true
show_absolute_path = false
## Incremental Mode
incremental = true
cache_dir = "~/.cache/mypy_cache"
sqlite_cache = true
cache_fine_grained = false
skip_version_check = false
#plugins = [""]
pdb = false
show_traceback = true
raise_exceptions = true
## Report generation
#Generating reports disables incremental mode and can significantly slow down your workflo
#any_exprs_report = ""
#html_report = ""
#linecount_report = ""
#lineprecision_report = ""
##Miscellaneous
#scripts_are_modules = true
warn_return_any = true
warn_unused_configs = true
verbosity = 2
#MyPy permodule
[[tool.mypy.overrides]]
module = ["google.oauth2.service_account"]
ignore_missing_imports = true
follow_imports_for_stubs = true
[[tool.mypy.overrides]]
module = ["gspread"]
ignore_missing_imports = true
follow_imports_for_stubs = true
[[tool.mypy.overrides]]
module = ["loguru"]
ignore_missing_imports = true
follow_imports_for_stubs = true
[[tool.mypy.overrides]]
module = ["dotenv"]
ignore_missing_imports = true
follow_imports_for_stubs = true
[[tool.mypy.overrides]]
[mypy-venv.Scripts]
file = ["venv\\Scripts\\activate_this.py"]
ignore_errors = true
exclude = ["venv\\Scripts\\activate_this.py"]
[[tool.mypy.overrides]]
