blank_issues_enabled: true
contact_links:
  - name: Repository Discussions
    url: https://github.com/iPoetDev/terni-lapilli--toe/discussions
    about: Open forum and contact point for this Javascript educational repositorty
  - name: Code Institute Student Handbook
    url: http://4060571.hs-sites.com/student-experience-handbook-2022/2023
    about: View Code Institute's policies and procedures in this comprehensive handbook.
  - name: Code Institute Tutoring Guidelines
    url: https://code-institute-org.github.io/tutoring-info/guidelines/
    about: Tutoring Guidelines from Code of Institute
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.